// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e


/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    if(!s) return t;
    let res = s[0].charCodeAt();
    for(let i = 1; i < s.length; i++){
        res ^= s[i].charCodeAt();
    }
    for(let i = 0; i < t.length; i++){
        res ^= t[i].charCodeAt();
    }
    
    return String.fromCharCode(res);
};